defaults: &defaults
  working_directory: ~/playbackloop
  docker:
    - image: circleci/ruby:2.3.7
      environment:
        PGHOST: localhost
        PGUSER: playbackloop
        RAILS_ENV: test
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: playbackloop
        POSTGRES_DB: playbackloop_test
        POSTGRES_PASSWORD: ""

# Cache Dependencies
cache_bundler: &cache_bundler
  type: cache-save
  name: Store bundle cache
  key: playbackloop-{{ checksum "Gemfile.lock" }}
  paths:
    - vendor/bundle

# Bundle install dependencies
bundle_install: &bundle_install
  run: bundle install --path vendor/bundle

# Restore Cached Dependencies
cache_restore: &cache_restore
  type: cache-restore
  name: Restore bundle cache
  key: playbackloop-{{ checksum "Gemfile.lock" }}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *cache_restore
      - *bundle_install
      - *cache_bundler
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:setup
      - run: bundle exec rake test

  deploy:
    <<: *defaults
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential python-dev python-pip
      - run: sudo pip install awscli
      - checkout
      - *cache_restore
      - *bundle_install
      - *cache_bundler
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:setup
      - run: ./bin/deploy production

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
